### ISSUE TITLE
Katex can't handle filenames with special chars

### ISSUE THREAD

**Issue by homelessgamer** [fabiocolacio/Marker#210] opened 2018-05-28 15:36 UTC
I am using the built-in Katex for maths-formulas and i just discovered, that the formula won't get compiled if the filename containing the code has a special char (in my case the german `ä`).

```
$ cat ä.md
$ bar() $
```

results in 
```
\( bar() \)
```

I installed Marker via flathub.

**Comment by fabiocolacio** [comment] 2018-05-29 00:21
This is a duplicate of #136. This is an issue with Webkit (we were able to reproduce it with GNOME Web also).

Documents with accents in the name are not able to access any linked documents (stylesheets, js extensions like math, etc.) for some reason.

**Closed by fabiocolacio** 2018-05-29 00:21 UTC
