### ISSUE TITLE
Error when building `master` on `archlinux`, with solution!

### ISSUE THREAD

**Issue by sasanj** [fabiocolacio/Marker#407] opened 2023-11-03 14:02 UTC
I'm using [`marker-git`](https://aur.archlinux.org/packages/marker-git) on AUR to build **Marker** . It has always build successfully, except now.
After some debugging, I found out that `_(x)` macro is not defined, and we need to include `glib/gi18n.h` where that macro is defined.
I don't know whether or not it is because of a  change in `glib`, but
 I include a patch to add mentioned correction to `src/marker.h`, which resolves this problem.
```diff
diff --git a/src/marker.h b/src/marker.h
index 334bc32a..fda32735 100644
--- a/src/marker.h
+++ b/src/marker.h
@@ -23,7 +23,7 @@
 #define __MARKER_H__
 
 #include <gtk/gtk.h>
-
+#include <glib/gi18n.h>
 GtkApplication      *marker_get_app                              (void);
 void                 marker_create_new_window                    (void);
 void                 marker_create_new_window_from_file          (GFile              *file);
```
[add_gi18n_h.patch.txt](https://github.com/fabiocolacio/Marker/files/13250979/add_gi18n_h.patch.txt)

**Comment by yochananmarqos** [comment] 2023-11-03 18:12
@sasanj his is a duplicate of #406, please close it.

**Closed** 2023-11-03 18:15 UTC
