### ISSUE TITLE
When typing something, preview automatically scrolls to the top

### ISSUE THREAD

**Issue by Mati20187** [fabiocolacio/Marker#191] opened 2018-04-11 19:30 UTC
Like in title, when i start typing something in Marker, preview window automatically scrolls to the top and if I want to see preview of what I typed, I have to scroll down every time. It's really annoying, is there any way to fix it?

**Comment by Mandarancio** [comment] 2018-04-12 00:26
Hi @Mati20187, have you installed it or only compiled and run locally?

**Comment by Mati20187** [comment] 2018-04-12 03:46
@Mandarancio I've installed it using yaourt -S marker

**Comment by Mandarancio** [comment] 2018-04-12 10:33
Could you try to install it manually from git? Other archers (see #187) had problem with the aur package..

**Comment by ronhasson** [comment] 2018-04-16 13:58
installing manually solves this problem

**Comment by ronhasson** [comment] 2018-04-16 15:07
have you deleted the AUR package before you installed manually?

**Comment by Mati20187** [comment] 2018-04-16 15:27
@ronhasson Yes, I have

**Comment by ronhasson** [comment] 2018-04-27 20:34
@Mati20187, mmetak made some changes to the AUR pkgbuild that fixed this and #187 for me.

try to install the new version from the AUR, and maybe also `marker-git` and not `marker` even tho it seems like mmetak fixed this one too

**Comment by ronhasson** [comment] 2018-08-22 15:44
Hello again, sorry I disappeared into the abyss for a while.
I'm actually able to reproduce it.

> 1. open a new file
> 2. fill the screen with titles and text
> 3. save the file and quit Marker
> 4. enter to the file, scroll the preview down and type new text

I'm using the latest AUR version (2018.07.03) and the issue is probably not linked to #187  since I can see charter normally.

**Comment by fabiocolacio** [comment] 2018-10-01 02:18
Hi @ronhasson,

I too took a break for a while haha; I hope all is well.

I am still unable to reproduce this... I have tested it with these two configurations:

Fedora 28: Both Compiled from source, and through Flatpak
Solus 3: Compiled from source

**Comment by tim77** [comment] 2019-05-11 18:08
I have this issue as well on Fedora 30. Latest Marker master version from git.

**Comment by Elnee** [comment] 2019-05-11 19:16
I also have that issue on Arch Linux 5.0.13-arch1-1.  
Both AUR and git versions.

**Comment by alerque** [comment] 2019-05-16 13:50
Same issue here. I just found Marker today and decided to give it a spin. Opening my current doc and starting to work from the end the very first thing I noticed was the preview jumping to the top, and I came here to file an issue report.

Archlinux latest stable (non git build) release from AUR.

**Comment by mrlinnth** [comment] 2019-07-12 01:43
Same issue. Installed it today on Linux Mint 19 from software manager.

Hope this gif helped with bug reproduction.

![scroll-bug](https://yanlinnthor.gitlab.io/uploads/2019/07/marker-scroll-bug.gif)

**Comment by nluizsoliveira** [comment] 2019-07-29 15:07
Same issue also on mint 19 from software manager

**Comment by johsteffens** [comment] 2019-08-24 15:17
I can reproduce it (Mint 19) and believe the issue is related to a recent deprecation of WebKit functionality.

[I created a workaround](https://github.com/johsteffens/Marker) and described it in a [readme-prefix](https://github.com/johsteffens/Marker/blob/master/README.md).

Let me know if that could be a solution.

Thanks for creating this tool.

Johannes

**Comment by Mandarancio** [comment] 2019-10-09 13:34
Hi it should be fixed now, could you please check and try?

**Comment by tim77** [comment] 2019-10-10 05:00
> Hi it should be fixed now, could you please check and try?

@Mandarancio can confirm, fixed now with version from master.
https://copr.fedorainfracloud.org/coprs/atim/marker/build/1051996/

**Closed** 2019-10-10 07:11 UTC
Labels: bug, not-reproducible

**Comment by johsteffens** [comment] 2019-10-15 09:58
@Mandarancio 
Thanks for working on this problem. I fear there are still a few issues, though. At least on Mint 19. They appeared with this recent change:

1. When editing outside a code block, preview scrolls to the changed position. That is great! However, the changed line appears at the bottom of the preview window; text below that line not visible. It would be nice to keep some text above and below that line in view.

2. When editing inside a code block, e.g.:
```C 
printf( "Hi Universe!\n" ); 
```
Then this specific issue remains: Preview scrolls back to the top.

3. When editing near a code block, e.g. one line above ```, the preview-code gets messed up. It seems in that situation the markdown parser does not recognize the beginning of a code block any more.

Hope that helps.

best

Johannes

**Comment by Mandarancio** [comment] 2019-10-15 11:08
Hi @johsteffens 
I know I already open a new issue (#283) about this (even if not as detailed as your report).

The problem that for the moment this solution is more a workaround/hack by locating an spam element in the markdown text, instead the solution should be implemented in the scidown render library. I wil try to implement it in the library as soon as possible.
If you have any other issue linked to this please fill free to comment the issue #283. 

Thanks!

M.

**Comment by johsteffens** [comment] 2019-10-15 11:51
Will do. Thanks.

**Comment by Esokrates** [comment] 2019-10-18 08:10
@Mandarancio Could you maybe make a new release, even if the issue is not 100% fixed? This issue affects the usability quite negatively. I recommended Marker to colleagues and the first feedback I got was the complaint about this issue. A release early release often model, paired with regular updating on flathub would help a lot with issues like that imho.
